[package]
name = "sticker-encoders"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
edition = "2018"

[dependencies]
conllx = "0.12.1"
edit_tree = "0.1.1"
failure = "0.1"
numberer = "0.1"
ordered-float = "1"
petgraph = "0.4"
serde = "1"
serde_derive = "1"
